import test from 'node:test';import assert from 'node:assert/strict';import {Model,PARTS,GROUPS,part,sideFaces,fullName,COLORS,anchor,UNIT} from '../dist/src/model.js';
const color=COLORS[0][1],at=(part,x,y,z,r=0)=>({part,x,y,z,r,color});
const find=(m,x,y,z)=>m.bricks.find(b=>b.x===x&&b.y===y&&b.z===z);
const FACES=['x-','x+','z-','z+'];

test('the catalog is well formed and every tab fits the 12-slot grid',()=>{const ids=new Set();for(const p of PARTS){assert.ok(!ids.has(p.id),p.id);ids.add(p.id);assert.ok(GROUPS.includes(p.group),p.id);for(const k of ['w','d','h'])assert.ok(Number.isInteger(p[k])&&p[k]>0,p.id+k);for(const f of [...(p.sideStuds||[]),...(p.sideHoles||[])])assert.ok(FACES.includes(f),p.id+f);if(p.sideStuds||p.sideHoles)assert.equal(p.h,3,p.id+' side features sit at brick height');}for(const g of GROUPS){const n=PARTS.filter(p=>p.group===g).length;assert.ok(n>0&&n<=12,g+' has '+n);}assert.ok(PARTS.length>=40);});
test('every piece has a readable full name',()=>{assert.equal(fullName(part('b24')),'Brick 2 × 4');assert.equal(fullName(part('s22')),'Slope 2 × 2');assert.match(fullName(part('n11o')),/side studs/i);assert.match(fullName(part('h11a')),/holes/i);});
test('side faces turn with the piece',()=>{assert.deepEqual([...sideFaces(at('n12o',0,0,0)).studs].sort(),['z+','z-']);assert.deepEqual([...sideFaces(at('n12o',0,0,0,1)).studs].sort(),['x+','x-']);assert.deepEqual([...sideFaces(at('h11o',0,0,0,1)).holes].sort(),['z+','z-']);assert.deepEqual([...sideFaces(at('n11a',0,0,0,3)).studs].sort(),[...FACES].sort());});

test('a side stud slots into a facing hole and holds the piece up',()=>{const m=new Model({gravity:true});m.add(at('b11',0,0,0));assert.equal(m.add(at('h11o',0,3,0)),null);assert.equal(m.add(at('n11o',1,3,0)),null);assert.equal(find(m,1,3,0).part,'n11o');});
test('a hole on every side takes studs from any direction',()=>{const m=new Model({gravity:true});m.add(at('b11',0,0,0));m.add(at('h11a',0,3,0));assert.equal(m.add(at('n11o',1,3,0)),null);assert.equal(m.add(at('n11o',-1,3,0)),null);assert.equal(m.add(at('n11o',0,3,1,1)),null);assert.equal(m.add(at('n11o',0,3,-1,1)),null);});
test('side studs cannot press against a plain wall, another stud or a misaligned hole',()=>{const m=new Model();m.add(at('b11',0,0,0));assert.match(m.add(at('n11o',1,0,0)),/side stud/i);const n=new Model();n.add(at('n11o',0,0,0));assert.match(n.add(at('n11o',1,0,0)),/side stud/i);assert.match(n.add(at('b12',1,0,0)),/side stud/i);assert.equal(n.add(at('b11',0,0,1)),null);const h=new Model();h.add(at('h11o',0,0,0));assert.match(h.add(at('n11o',1,1,0)),/side stud/i);assert.equal(h.add(at('n11o',1,0,0)),null);});
test('holes only on the far sides leave the near faces plain',()=>{const m=new Model();m.add(at('h11o',0,0,0));assert.match(m.add(at('n11o',0,0,1,1)),/side stud/i);});
test('with gravity on, a piece held only by a side stud is accepted and one with no grip is refused',()=>{const m=new Model({gravity:true});m.add(at('b11',0,0,0));m.add(at('b11',0,3,0));assert.match(m.add(at('b11',1,3,0)),/holding/);});
test('pieces gripped sideways fall together when their support goes',()=>{const m=new Model({gravity:true});m.add(at('b11',0,0,0));m.add(at('h11o',0,3,0));m.add(at('n11o',1,3,0));m.remove(find(m,0,0,0).id);assert.equal(m.fallen,2);assert.equal(find(m,0,0,0).part,'h11o');assert.equal(find(m,1,0,0).part,'n11o');});
test('a side grip carries a bridge across a gap',()=>{const m=new Model({gravity:true});for(const b of [at('b11',0,0,0),at('h11o',0,3,0),at('n11o',1,3,0),at('h11o',2,3,0),at('b11',2,6,0)])assert.equal(m.add(b),null);assert.equal(m.bricks.length,5);});
test('batch placement checks side clashes and side grips across the batch',()=>{const m=new Model({gravity:true});assert.equal(m.addMany([at('n11o',1,3,0),at('h11o',0,3,0),at('b11',0,0,0)]),null);assert.match(m.addMany([at('b11',5,0,5),at('n11o',6,0,5)]),/side stud/i);assert.equal(m.bricks.length,3);});
test('moving a stud brick away from its hole lets it fall when gravity is on',()=>{const m=new Model({gravity:true});m.add(at('b11',0,0,0));m.add(at('h11o',0,3,0));m.add(at('n11o',1,3,0));m.add(at('p11',1,6,0));const stud=find(m,1,3,0);assert.match(m.update(stud.id,{x:3}),/holding/);});
test('links in a row slot into each other and carry a sideways chain from one support',()=>{const m=new Model({gravity:true});m.add(at('b11',0,0,0));for(let x=0;x<4;x++)assert.equal(m.add(at('l11r',x,3,0)),null,'link '+x);assert.equal(m.bricks.length,5);m.remove(find(m,0,0,0).id);assert.equal(m.fallen,4);assert.deepEqual(m.bricks.map(b=>b.y),[0,0,0,0]);});
test('a link turned the wrong way meets hole to hole and does not grip',()=>{const m=new Model({gravity:true});m.add(at('b11',0,0,0));m.add(at('l11r',0,3,0));assert.match(m.add(at('l11r',1,3,0,2)),/holding/);});
test('a link\'s studs still clash with a plain face',()=>{const m=new Model();m.add(at('b11',0,0,0));assert.match(m.add(at('l11r',1,0,0)),/side stud/i);});
test('grid links grip neighbours in both directions',()=>{const m=new Model({gravity:true});m.add(at('b11',0,0,0));for(const [x,z] of [[0,0],[1,0],[0,1],[1,1]])assert.equal(m.add(at('l11g',x,3,z)),null,`link ${x},${z}`);});
test('side-by-side and end-to-end links chain along the faces they are named for',()=>{const m=new Model({gravity:true});m.add(at('b12',0,0,0));m.add(at('l12s',0,3,0));assert.equal(m.add(at('l12s',0,3,1)),null);assert.equal(m.add(at('l14s',0,3,2)),null);const e=new Model({gravity:true});e.add(at('b12',0,0,0));e.add(at('l12e',0,3,0));assert.equal(e.add(at('l12e',2,3,0)),null);assert.match(e.add(at('l12e',0,3,1)),/holding/);});

// A pointer hit at plate-unit height y, in world space as the raycaster reports it. Faces sit a hair inside the stud grid.
const pt=(x,y,z)=>({x,y:y*UNIT,z}),IN=.0225;
test('a hit on a wall above the plate anchors the piece beside it, on the same course, and it grips',()=>{const m=new Model({gravity:true});m.add(at('b11',0,0,0));m.add(at('h11o',0,3,0));const spot=anchor(find(m,0,3,0),pt(1-IN,4.5,.5),part('n11o'),0);assert.deepEqual(spot,{x:1,y:3,z:0});assert.equal(m.add(at('n11o',spot.x,spot.y,spot.z)),null);});
test('the face is found from the world point, so a turned target anchors on its world face',()=>{const m=new Model({gravity:true});m.add(at('b12',0,0,0,1));m.add(at('h12o',0,3,0,1));const spot=anchor(find(m,0,3,0),pt(1-IN,4,1.4),part('n11o'),0);assert.deepEqual(spot,{x:1,y:3,z:1});assert.equal(m.add(at('n11o',spot.x,spot.y,spot.z)),null);});
test('each wall sets a wider piece flush against it',()=>{const t=at('b11',0,3,0),p=part('b12');assert.deepEqual(anchor(t,pt(IN,4,.5),p,0),{x:-2,y:3,z:0});assert.deepEqual(anchor(t,pt(.5,4,IN),p,1),{x:0,y:3,z:-2});assert.deepEqual(anchor(t,pt(.5,4,1-IN),p,1),{x:0,y:3,z:1});assert.deepEqual(anchor(at('b14',0,0,0),pt(3.9,1.5,1-IN),p,0),{x:3,y:0,z:1});});
test('a hit on the top or its studs still stacks on top, and the plate still places on the ground',()=>{const t=at('h11o',0,3,0),p=part('b11'),top=6-.0175/UNIT;assert.deepEqual(anchor(t,pt(.5,top,.5),p,0),{x:0,y:6,z:0});assert.deepEqual(anchor(t,pt(.1,top,.9),p,0),{x:0,y:6,z:0});assert.deepEqual(anchor(t,pt(.6,6.5,.4),p,0),{x:0,y:6,z:0});assert.deepEqual(anchor(null,pt(3.2,0,-1.7),p,0),{x:3,y:0,z:-2});});
test('a shorter piece goes as high up a taller wall as the point, never past its top or bottom',()=>{const t=at('b11',0,3,0),p=part('p11');assert.equal(anchor(t,pt(1-IN,5.8,.5),p,0).y,5);assert.equal(anchor(t,pt(1-IN,4.4,.5),p,0).y,4);assert.equal(anchor(t,pt(1-IN,3.2,.5),p,0).y,3);assert.equal(anchor(at('p11',0,3,0),pt(1-IN,3.5,.5),part('b11'),0).y,3);});
