import test from 'node:test';import assert from 'node:assert/strict';import {Model,PARTS,GROUPS,part,sideFaces,fullName,COLORS} from '../dist/src/model.js';
const color=COLORS[0][1],at=(part,x,y,z,r=0)=>({part,x,y,z,r,color});
const find=(m,x,y,z)=>m.bricks.find(b=>b.x===x&&b.y===y&&b.z===z);
const FACES=['x-','x+','z-','z+'];

test('the catalog is well formed and every tab fits the 12-slot grid',()=>{const ids=new Set();for(const p of PARTS){assert.ok(!ids.has(p.id),p.id);ids.add(p.id);assert.ok(GROUPS.includes(p.group),p.id);for(const k of ['w','d','h'])assert.ok(Number.isInteger(p[k])&&p[k]>0,p.id+k);for(const f of [...(p.sideStuds||[]),...(p.sideHoles||[])])assert.ok(FACES.includes(f),p.id+f);if(p.sideStuds||p.sideHoles)assert.equal(p.h,3,p.id+' side features sit at brick height');}for(const g of GROUPS){const n=PARTS.filter(p=>p.group===g).length;assert.ok(n>0&&n<=12,g+' has '+n);}assert.ok(PARTS.length>=40);});
test('every piece has a readable full name',()=>{assert.equal(fullName(part('b24')),'Brick 2 × 4');assert.equal(fullName(part('s22')),'Slope 2 × 2');assert.match(fullName(part('n11o')),/side studs/i);assert.match(fullName(part('h11a')),/holes/i);});
test('side faces turn with the piece',()=>{assert.deepEqual([...sideFaces(at('n12o',0,0,0)).studs].sort(),['z+','z-']);assert.deepEqual([...sideFaces(at('n12o',0,0,0,1)).studs].sort(),['x+','x-']);assert.deepEqual([...sideFaces(at('h11o',0,0,0,1)).holes].sort(),['z+','z-']);assert.deepEqual([...sideFaces(at('n11a',0,0,0,3)).studs].sort(),[...FACES].sort());});

test('a side stud slots into a facing hole and holds the piece up',()=>{const m=new Model({gravity:true});m.add(at('b11',0,0,0));assert.equal(m.add(at('h11o',0,3,0)),null);assert.equal(m.add(at('n11o',1,3,0)),null);assert.equal(find(m,1,3,0).part,'n11o');});
test('a hole on every side takes studs from any direction',()=>{const m=new Model({gravity:true});m.add(at('b11',0,0,0));m.add(at('h11a',0,3,0));assert.equal(m.add(at('n11o',1,3,0)),null);assert.equal(m.add(at('n11o',-1,3,0)),null);assert.equal(m.add(at('n11o',0,3,1,1)),null);assert.equal(m.add(at('n11o',0,3,-1,1)),null);});
test('side studs cannot press against a plain wall, another stud or a misaligned hole',()=>{const m=new Model();m.add(at('b11',0,0,0));assert.match(m.add(at('n11o',1,0,0)),/side stud/i);const n=new Model();n.add(at('n11o',0,0,0));assert.match(n.add(at('n11o',1,0,0)),/side stud/i);assert.match(n.add(at('b12',1,0,0)),/side stud/i);assert.equal(n.add(at('b11',0,0,1)),null);const h=new Model();h.add(at('h11o',0,0,0));assert.match(h.add(at('n11o',1,1,0)),/side stud/i);assert.equal(h.add(at('n11o',1,0,0)),null);});
test('holes only on the far sides leave the near faces plain',()=>{const m=new Model();m.add(at('h11o',0,0,0));assert.match(m.add(at('n11o',0,0,1,1)),/side stud/i);});
test('with gravity on, a piece held only by a side stud is accepted and one with no grip is refused',()=>{const m=new Model({gravity:true});m.add(at('b11',0,0,0));m.add(at('b11',0,3,0));assert.match(m.add(at('b11',1,3,0)),/holding/);});
test('pieces gripped sideways fall together when their support goes',()=>{const m=new Model({gravity:true});m.add(at('b11',0,0,0));m.add(at('h11o',0,3,0));m.add(at('n11o',1,3,0));m.remove(find(m,0,0,0).id);assert.equal(m.fallen,2);assert.equal(find(m,0,0,0).part,'h11o');assert.equal(find(m,1,0,0).part,'n11o');});
test('a side grip carries a bridge across a gap',()=>{const m=new Model({gravity:true});for(const b of [at('b11',0,0,0),at('h11o',0,3,0),at('n11o',1,3,0),at('h11o',2,3,0),at('b11',2,6,0)])assert.equal(m.add(b),null);assert.equal(m.bricks.length,5);});
test('batch placement checks side clashes and side grips across the batch',()=>{const m=new Model({gravity:true});assert.equal(m.addMany([at('n11o',1,3,0),at('h11o',0,3,0),at('b11',0,0,0)]),null);assert.match(m.addMany([at('b11',5,0,5),at('n11o',6,0,5)]),/side stud/i);assert.equal(m.bricks.length,3);});
test('moving a stud brick away from its hole lets it fall when gravity is on',()=>{const m=new Model({gravity:true});m.add(at('b11',0,0,0));m.add(at('h11o',0,3,0));m.add(at('n11o',1,3,0));m.add(at('p11',1,6,0));const stud=find(m,1,3,0);assert.match(m.update(stud.id,{x:3}),/holding/);});
