import test from 'node:test';import assert from 'node:assert/strict';import {Model,starter,validateProject,COLORS,PARTS} from '../dist/src/model.js';
const b={part:'b24',x:0,y:0,z:0,r:0,color:COLORS[0][1]};
test('snapping volumes reject overlap and allow exact stacking',()=>{const m=new Model();assert.equal(m.add(b),null);assert.equal(m.add({...b,x:1}),'Space is occupied');assert.equal(m.add({...b,y:3}),null);assert.equal(m.bricks.length,2);});
test('rotated extents enforce board edges',()=>{const m=new Model();assert.equal(m.add({...b,x:14,r:1}),null);assert.equal(m.add({...b,x:14,z:8}),'Outside the build plate');});
test('move, paint, delete, undo and redo preserve full state',()=>{const m=new Model();m.add(b);const id=m.bricks[0].id;m.update(id,{x:4,color:COLORS[2][1]});assert.equal(m.bricks[0].x,4);m.remove(id);assert.equal(m.bricks.length,0);m.undo();assert.equal(m.bricks[0].color,COLORS[2][1]);m.undo();assert.equal(m.bricks[0].x,0);m.redo();assert.equal(m.bricks[0].x,4);m.add({...b,z:5});assert.equal(m.future.length,0);});
test('invalid imports leave current project and history intact',()=>{const m=new Model();m.add(b);const before=m.serialize();assert.throws(()=>m.replace({...before,bricks:[...before.bricks,...before.bricks]}));assert.deepEqual(m.serialize(),before);assert.equal(m.past.length,1);assert.throws(()=>validateProject({...before,bricks:[{...before.bricks[0],x:NaN}]}));assert.throws(()=>validateProject({...before,bricks:[{...before.bricks[0],r:8}]}));});
test('all starter models round-trip with no collision or invalid pieces',()=>{for(const kind of ['blank','studio','tower']){const data=starter(kind);assert.deepEqual(validateProject(data),{name:data.name,bricks:data.bricks});}});
test('capacity and import bounds reject pathological data',()=>{const d=starter('blank');assert.throws(()=>validateProject({...d,bricks:Array(2001).fill(b)}));assert.throws(()=>validateProject({...d,version:99}));});
test('2000-piece scene validates within a bounded budget',()=>{const m=new Model();const start=performance.now();for(let i=0;i<2000;i++){const err=m.valid({...b,part:'b11',x:(i%32)-16,z:Math.floor(i/32)%32-16,y:Math.floor(i/1024)*3});assert.equal(err,null);m.bricks.push({...b,part:'b11',id:String(i),x:(i%32)-16,z:Math.floor(i/32)%32-16,y:Math.floor(i/1024)*3});}const data=m.serialize();assert.equal(validateProject(data).bricks.length,2000);console.log('2000-piece collision + import validation:',Math.round(performance.now()-start),'ms');});
