import test from 'node:test';import assert from 'node:assert/strict';import {Model,starter,validateProject,settle,COLORS} from '../dist/src/model.js';
const color=COLORS[0][1],at=(part,x,y,z,r=0)=>({part,x,y,z,r,color});
const find=(m,x,y,z)=>m.bricks.find(b=>b.x===x&&b.y===y&&b.z===z);
// A pillar of two 1×1 bricks at x=0 topped by a 1×4 bridge reaching to x=4.
function bridge(){const m=new Model();for(const b of [at('b11',0,0,0),at('b11',0,3,0),at('b14',0,6,0)])assert.equal(m.add(b),null);return m;}

test('pieces cannot be placed in mid-air',()=>{const m=new Model();assert.match(m.add(at('b24',0,6,0)),/holding/);assert.equal(m.bricks.length,0);assert.equal(m.add(at('b24',0,0,0)),null);});
test('pieces rest on the plate, stack, and cantilever from a single stud',()=>{const m=new Model();assert.equal(m.add(at('b11',0,0,0)),null);assert.equal(m.add(at('b24',0,3,0)),null);assert.equal(m.add(at('b24',3,6,1)),null);});
test('studded pieces hang beneath a held piece; smooth-topped pieces cannot',()=>{const m=bridge();assert.equal(m.add(at('b11',3,3,0)),null);assert.match(m.add(at('t12',1,5,0)),/holding/);});
test('tiles and slopes carry weight but nothing hangs from them',()=>{const m=new Model();assert.equal(m.add(at('t22',0,0,0)),null);assert.equal(m.add(at('b22',0,1,0)),null);assert.equal(m.add(at('s22',4,0,0)),null);assert.equal(m.add(at('b22',4,3,0)),null);});
test('raising a piece off its support is rejected',()=>{const m=new Model();m.add(at('b22',0,0,0));assert.match(m.update(m.bricks[0].id,{y:1}),/holding/);assert.equal(m.bricks[0].y,0);});
test('removing a support makes the pieces above fall, and undo restores them',()=>{const m=new Model();m.add(at('b11',0,0,0));m.add(at('b11',0,3,0));m.add(at('p11',0,6,0));m.remove(find(m,0,0,0).id);assert.equal(m.fallen,2);assert.deepEqual(m.bricks.map(b=>[b.part,b.y]).sort(),[['b11',0],['p11',3]]);m.undo();assert.equal(m.fallen,0);assert.deepEqual(m.bricks.map(b=>b.y).sort((a,b)=>a-b),[0,3,6]);});
test('gripped pieces fall together as one rigid group',()=>{const m=bridge();m.add(at('b11',3,3,0));m.remove(find(m,0,0,0).id);assert.equal(m.fallen,3);assert.ok(find(m,0,0,0)&&find(m,3,0,0));assert.equal(find(m,0,3,0).part,'b14');});
test('a piece resting on a smooth top falls separately from the piece below it',()=>{const m=new Model();m.add(at('b22',0,0,0));m.add(at('t22',0,3,0));m.add(at('b22',0,4,0));m.add(at('b11',4,0,0));m.remove(find(m,0,0,0).id);assert.deepEqual(m.bricks.filter(b=>b.x===0).map(b=>[b.part,b.y]),[['t22',0],['b22',1]]);});
test('a falling group lands on the highest surface beneath any of its pieces',()=>{const m=bridge();m.add(at('b11',3,0,0));m.add(at('p11',3,3,0));m.remove(find(m,0,0,0).id);assert.equal(m.fallen,2);assert.equal(find(m,0,4,0).part,'b14');assert.equal(find(m,0,1,0).part,'b11');});
test('moving a support away lets what it held fall',()=>{const m=new Model();m.add(at('b22',0,0,0));m.add(at('b22',0,3,0));const base=find(m,0,0,0);assert.equal(m.update(base.id,{x:6}),null);assert.equal(m.fallen,1);assert.ok(find(m,0,0,0)&&find(m,6,0,0));});
test('a piece cannot be moved to hang from what only it was holding up',()=>{const m=bridge();const pillarTop=find(m,0,3,0);assert.match(m.update(pillarTop.id,{x:3}),/holding/);});
test('imports settle floating pieces instead of rejecting the project',()=>{const data={format:'bricklab',version:1,name:'Floaty',bricks:[{id:'a',...at('b22',0,9,0)},{id:'b',...at('p22',0,12,0)},{id:'c',...at('b11',5,0,5)}]};const clean=validateProject(data);assert.deepEqual(clean.bricks.map(b=>[b.id,b.y]),[['a',0],['b',3],['c',0]]);});
test('settle leaves an already-held build untouched',()=>{const data=starter('studio');const result=settle(data.bricks);assert.equal(result.fallen,0);assert.equal(result.bricks,data.bricks);});
test('every starter build is fully held with nothing to settle',()=>{for(const kind of ['blank','studio','tower']){const data=starter(kind);assert.equal(settle(data.bricks).fallen,0,kind);assert.ok(data.bricks.length>0||kind==='blank');}});
test('batch placement checks support across the whole batch and is atomic',()=>{const m=new Model();assert.equal(m.addMany([at('b11',3,3,0),at('b14',0,6,0),at('b11',0,0,0),at('b11',0,3,0)]),null);assert.equal(m.bricks.length,4);assert.equal(m.past.length,1);assert.match(m.addMany([at('b11',10,0,10),at('b11',10,6,10)]),/holding/);assert.equal(m.bricks.length,4);assert.match(m.addMany([at('b11',12,0,12),at('b11',12,0,12)]),/occupied/);assert.equal(m.bricks.length,4);});
test('with gravity off, pieces can float and stay put when their support goes',()=>{const m=new Model();m.gravity=false;assert.equal(m.add(at('b22',0,6,0)),null);m.add(at('b22',4,0,0));m.add(at('b22',4,3,0));m.remove(find(m,4,0,0).id);assert.equal(m.fallen,0);assert.ok(find(m,4,3,0)&&find(m,0,6,0));assert.equal(m.addMany([at('b11',10,9,10)]),null);});
test('turning gravity on settles floating pieces, and undo restores both the setting and the positions',()=>{const m=new Model();m.gravity=false;m.add(at('b22',0,6,0));m.add(at('p22',0,9,0));m.setGravity(true);assert.equal(m.gravity,true);assert.equal(m.fallen,2);assert.deepEqual(m.bricks.map(b=>b.y),[0,3]);m.undo();assert.equal(m.gravity,false);assert.deepEqual(m.bricks.map(b=>b.y),[6,9]);m.redo();assert.equal(m.gravity,true);assert.deepEqual(m.bricks.map(b=>b.y),[0,3]);});
test('setting gravity to its current value records nothing',()=>{const m=new Model();m.setGravity(true);assert.equal(m.past.length,0);});
test('imports keep floating pieces when gravity is off, and project files never carry the setting',()=>{const data={format:'bricklab',version:1,name:'Floaty',bricks:[{id:'a',...at('b22',0,9,0)}]};assert.equal(validateProject(data,{gravity:false}).bricks[0].y,9);assert.equal(validateProject(data).bricks[0].y,0);const m=new Model();m.gravity=false;m.replace(data);assert.equal(m.bricks[0].y,9);assert.equal('gravity' in m.serialize(),false);});
