import test from 'node:test';import assert from 'node:assert/strict';import {Model,COLORS,UNHELD} from '../dist/src/model.js';import {SLOTS,slotAt,slotAngle,tweak,blockedSlots,wheelCentre,stickyLabel} from '../dist/src/wheel.js';
const color=COLORS[0][1],at=(part,x,y,z,r=0)=>({part,x,y,z,r,color});

test('eight slots in fixed compass order, clockwise from north',()=>{assert.deepEqual(SLOTS.map(s=>s.id),['raise','paint','rotate','copy','lower','delete','move','use']);assert.equal(new Set(SLOTS.map(s=>s.key)).size,8);});
test('a pointer offset picks the slot it points at, and the dead zone picks none',()=>{assert.equal(slotAt(0,-50,20),0);assert.equal(slotAt(50,0,20),2);assert.equal(slotAt(0,50,20),4);assert.equal(slotAt(-50,0,20),6);assert.equal(slotAt(40,-40,20),1);assert.equal(slotAt(-40,-40,20),7);assert.equal(slotAt(5,-5,20),-1);});
test('slot angles and slotAt agree for every slot',()=>{for(let i=0;i<8;i++){const a=slotAngle(i);assert.equal(slotAt(Math.cos(a)*60,Math.sin(a)*60,20),i);}});
test('tweaks raise, lower and turn a quarter',()=>{const b=at('b24',0,3,0,3);assert.deepEqual(tweak('raise',b),{y:4});assert.deepEqual(tweak('lower',b),{y:2});assert.deepEqual(tweak('rotate',b),{r:0});assert.equal(tweak('paint',b),null);});
test('lowering a piece on the plate is blocked by the plate',()=>{const m=new Model();m.add(at('b22',0,0,0));assert.equal(blockedSlots(m,m.bricks[0]).lower,'The plate is in the way');});
test('a piece above blocks raising, a neighbour blocks rotating',()=>{const m=new Model();m.add(at('b11',0,0,0));m.add(at('b11',0,3,0));m.add(at('b12',4,0,0));m.add(at('b11',4,0,1));const low=m.bricks[0],bar=m.bricks[2];assert.equal(blockedSlots(m,low).raise,'Space is occupied');assert.equal(blockedSlots(m,bar).rotate,'Space is occupied');assert.equal(blockedSlots(m,m.bricks[1]).raise,undefined);});
test('with gravity on, lifting a grounded piece off its support is blocked',()=>{const m=new Model({gravity:true});m.add(at('b22',0,0,0));assert.equal(blockedSlots(m,m.bricks[0]).raise,UNHELD);const free=new Model({gravity:false});free.add(at('b22',0,0,0));assert.equal(blockedSlots(free,free.bricks[0]).raise,undefined);});
test('the wheel centre stays on the piece unless that would push the wheel off screen',()=>{assert.deepEqual(wheelCentre(500,400,100,1200,800),{x:500,y:400});assert.deepEqual(wheelCentre(20,30,100,1200,800),{x:108,y:108});assert.deepEqual(wheelCentre(1190,790,100,1200,800),{x:1092,y:692});});
test('sticky modes describe themselves in plain words',()=>{assert.equal(stickyLabel({id:'paint',color:'#ef6454'}),'Painting Coral');assert.equal(stickyLabel({id:'delete'}),'Deleting');assert.equal(stickyLabel({id:'copy'}),'Copying');});
